import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "./components";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Praiz | Innovative & Creative",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="relative h-full min-h-full w-full overflow-hidden select-none">
			<body className={poppins.className}>
				<main className="bg-primary">
					<Header />

					{children}
				</main>
			</body>
		</html>
	);
}
