import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Card } from "./components";
import { Header } from "./components/Global/_header.tsx/header";
import { Background } from "./components/Global/background";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Praiz | Innovative & Creative",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="relative h-full min-h-full w-full overflow-hidden select-none">
			<body className={poppins.className}>
				<Card>
					<Header />
					<Background />

					{children}
				</Card>
			</body>
		</html>
	);
}
