import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Footer, Header, StarsCanvas } from "../components";
import "./globals.css";
const poppins = Poppins({
	weight: ["500", "400", "900", "600"],
	subsets: ["latin"],
	style: "normal",
	preload: false,
	fallback: [
		"Segoe UI",
		"Roboto",
		"Helvetica Neue",
		"Open Sans",
		"Ubuntu",
		"sans-serif",
	],
});

export const metadata: Metadata = {
	title: "Praiz | Innovative & Creative",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.className}  bg-primary overflow-x-hidden`}>
				<StarsCanvas />
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
