import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Particles } from "../components";
import "./globals.css";

const poppins = Poppins({
	weight: ["500", "400", "900", "600"],
	subsets: ["latin"],
	style: "normal",
	preload: false,
	fallback: [
		"Segoe UI",
		"Roboto",
		"Helvetica Neue",
		"Open Sans",
		"Ubuntu",
		"sans-serif",
	],
});

export const metadata: Metadata = {
	title: "Nnaji | Innovative & Creative",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`${poppins.className} relative  antialiased bg-primary`}>
				<Particles
					className="fixed -z-10 size-full inset-0"
					quantity={500}
					ease={80}
					refresh
					color="#F7FFF7"
				/>
				<main>{children}</main>
			</body>
		</html>
	);
}
